 name: Node CI
 on:
   - push
 jobs:
   build:

     rins-on: ubuntu-latest
     strategy:
       matrix:
         node-version: [14.x]
     steps:
       - uses: actions/checkout@v2
       - name: Use Node
       - uses: actions/setup-node@v1
         with:
           node-version: ${{ matrix.node-version }}
       - name: npm install
         run:  make install
         env:
           CI: true
       - name: Linter
         run:  make lint
